<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <TargetFrameworks>net45;netstandard2.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <IncludeSourceRevisionInInformationalVersion>False</IncludeSourceRevisionInInformationalVersion>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>OtiiTcpClient.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyVersion>1.0.8.0</AssemblyVersion>
    <PackageReleaseNotes>Added Arc.GetMain().</PackageReleaseNotes>
    <Copyright>Copyright © 2024</Copyright>
  </PropertyGroup>
  <PropertyGroup>
    <Title>Otii Tcp Client</Title>
    <Authors>qoitech</Authors>
    <Company>Qoitech AB</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>images\icon.png</PackageIcon>
    <PackageProjectUrl>https://github.com/qoitech/otii-tcp-client-csharp</PackageProjectUrl>
    <PackageIconUrl>https://www.qoitech.com/images/otii-128x128.png</PackageIconUrl>
    <Description>Otii TCP Client to be used with Otii Automation Toolbox.</Description>
    <AssemblyTitle>$(Title)</AssemblyTitle>
    <VersionPrefix>$(AssemblyVersion)</VersionPrefix>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <None Include="images\icon.png">
      <Pack>True</Pack>
      <PackagePath>\images\</PackagePath>
    </None>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>